version: '3'
services:
  db:
    image: postgres

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  node:
    image: "node:8"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"

  auctions:
    build: .
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - node
