default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 20
  host: localhost

development:
  <<: *default
  database: webapp_development
  host: db

test:
  <<: *default
  database: webapp_test
  host: db

production:
  <<: *default
  database:
  password:
